library(randomForest)
library(tictoc)

setwd("C:/Users/hkaus/OneDrive/Dokumente/Bachelorarbeit/heiko-kauschke-bachelor/Implementation/Datensets")

train.test.classification <- function(trainData, testData) {
  train <- read.csv(trainData)
  train$class <- as.factor(train$class)
  tic(trainData)
  fit <- randomForest(formula = class ~ ., data = train, ntree = 100)
  toc(log = TRUE)
  test <- read.csv(testData)
  prediction <- predict(fit, newdata = test, type = "class")
  true <- prediction == test$class
  precision <- sum(true) / length(true)
  print(c("Precision:", precision))
  return(precision)
}

run.iris <- function() {
  print("Training iris: Set1")
  set.seed(1)
  p1 <- train.test.classification('iris_train1.csv', 'iris_test1.csv')
  print('----------------------------------------------------------')
  print("Training iris: Set2")
  set.seed(2)
  p2 <- train.test.classification('iris_train2.csv', 'iris_test2.csv')
  print('----------------------------------------------------------')
  print("Training iris: Set3")
  set.seed(3)
  p3 <- train.test.classification('iris_train3.csv', 'iris_test3.csv')
  print('----------------------------------------------------------')
  print("Training iris: Set4")
  set.seed(4)
  p4 <- train.test.classification('iris_train4.csv', 'iris_test4.csv')
  print('----------------------------------------------------------')
  print("Training iris: Set5")
  set.seed(5)
  p5 <- train.test.classification('iris_train5.csv', 'iris_test5.csv')
  print('----------------------------------------------------------')
  log.lst <- tic.log(format = FALSE)
  tic.clearlog()
  timings <- unlist(lapply(log.lst, function(x) x$toc - x$tic))
  mp <- mean(c(p1,p2,p3,p4,p5))
  variance <- var(timings)
  abw <- sqrt(variance)
  err <- abw / sqrt(length(timings))
  print(c('Average Train Time:', mean(timings)))
  print(c('Standard Error of Mean(Time:)', err))
  print(c('Average Precision:', mp))
  print('--------------------------------------------')
  print('--------------------------------------------')
}
sink("Iris_forest_R.txt")
run.iris()
sink()

run.digits <- function() {
  print("Training digits: Set1")
  set.seed(1)
  p1 <- train.test.classification('digits_train1.csv', 'digits_test1.csv')
  print('----------------------------------------------------------')
  print("Training digits: Set2")
  set.seed(2)
  p2 <- train.test.classification('digits_train2.csv', 'digits_test2.csv')
  print('----------------------------------------------------------')
  print("Training digits: Set3")
  set.seed(3)
  p3 <- train.test.classification('digits_train3.csv', 'digits_test3.csv')
  print('----------------------------------------------------------')
  print("Training digits: Set4")
  set.seed(4)
  p4 <- train.test.classification('digits_train4.csv', 'digits_test4.csv')
  print('----------------------------------------------------------')
  print("Training digits: Set5")
  set.seed(5)
  p5 <- train.test.classification('digits_train5.csv', 'digits_test5.csv')
  print('----------------------------------------------------------')
  log.lst <- tic.log(format = FALSE)
  tic.clearlog()
  timings <- unlist(lapply(log.lst, function(x) x$toc - x$tic))
  mp <- mean(c(p1,p2,p3,p4,p5))
  variance <- var(timings)
  abw <- sqrt(variance)
  err <- abw / sqrt(length(timings))
  print(c('Average Train Time:', mean(timings)))
  print(c('Standard Error of Mean(Time:)', err))
  print(c('Average Precision:', mp))
  print('--------------------------------------------')
  print('--------------------------------------------')
}
sink("Digits_forest_R.txt")
run.digits()
sink()

train.test.regression <- function(trainData, testData) {
  train <- read.csv(trainData)
  tic(trainData)
  fit <- randomForest(formula = Y ~ ., data = train, ntree = 100)
  toc(log = TRUE)
  test <- read.csv(testData)
  prediction <- predict(fit, newdata = test)
  mse <- sum((prediction - test$Y)**2) / length(test$Y)
  print(c("Mean-Squared-Error:", mse))
  return(mse)
}

run.diabetes <- function() {
  print("Training diabetes: Set1")
  set.seed(1)
  p1 <- train.test.regression('diabetes_train1.csv', 'diabetes_test1.csv')
  print('----------------------------------------------------------')
  print("Training diabetes: Set2")
  set.seed(2)
  p2 <- train.test.regression('diabetes_train2.csv', 'diabetes_test2.csv')
  print('----------------------------------------------------------')
  print("Training diabetes: Set3")
  set.seed(3)
  p3 <- train.test.regression('diabetes_train3.csv', 'diabetes_test3.csv')
  print('----------------------------------------------------------')
  print("Training diabetes: Set4")
  set.seed(4)
  p4 <- train.test.regression('diabetes_train4.csv', 'diabetes_test4.csv')
  print('----------------------------------------------------------')
  print("Training diabetes: Set5")
  set.seed(5)
  p5 <- train.test.regression('diabetes_train5.csv', 'diabetes_test5.csv')
  print('----------------------------------------------------------')
  log.lst <- tic.log(format = FALSE)
  tic.clearlog()
  timings <- unlist(lapply(log.lst, function(x) x$toc - x$tic))
  mp <- mean(p1,p2,p3,p4,p5)
  variance <- var(timings)
  abw <- sqrt(variance)
  err <- abw / sqrt(length(timings))
  print(c('Average Train Time:', mean(timings)))
  print(c('Standard Error of Mean(Time:)', err))
  print(c('Average MSE:', mp))
  print('--------------------------------------------')
  print('--------------------------------------------')
}
sink("Diabetes_forest_R.txt")
run.diabetes()
sink()

run.california <- function() {
  print("Training california: Set1")
  set.seed(1)
  p1 <- train.test.regression('california_train1.csv', 'california_test1.csv')
  print('----------------------------------------------------------')
  print("Training california: Set2")
  set.seed(2)
  p2 <- train.test.regression('california_train2.csv', 'california_test2.csv')
  print('----------------------------------------------------------')
  print("Training california: Set3")
  set.seed(3)
  p3 <- train.test.regression('california_train3.csv', 'california_test3.csv')
  print('----------------------------------------------------------')
  print("Training california: Set4")
  set.seed(4)
  p4 <- train.test.regression('california_train4.csv', 'california_test4.csv')
  print('----------------------------------------------------------')
  print("Training california: Set5")
  set.seed(5)
  p5 <- train.test.regression('california_train5.csv', 'california_test5.csv')
  print('----------------------------------------------------------')
  log.lst <- tic.log(format = FALSE)
  tic.clearlog()
  timings <- unlist(lapply(log.lst, function(x) x$toc - x$tic))
  mp <- mean(p1,p2,p3,p4,p5)
  variance <- var(timings)
  abw <- sqrt(variance)
  err <- abw / sqrt(length(timings))
  print(c('Average Train Time:', mean(timings)))
  print(c('Standard Error of Mean(Time:)', err))
  print(c('Average MSE:', mp))
  print('--------------------------------------------')
  print('--------------------------------------------')
}
sink("California_forest_R.txt")
run.california()
sink()


